apiVersion: v1
kind: Service
metadata:
  name: gost-public-sidecar
  labels:
    app.kubernetes.io/name: gost-public-sidecar
    app.kubernetes.io/part-of: freeproxyapi
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gost-public-sidecar
  ports:
    - name: http-proxy
      port: 3128
      targetPort: http-proxy
    - name: country-http
      port: 3129
      targetPort: country-http
    - name: country-http-2
      port: 3130
      targetPort: country-http-2
    - name: country-http-3
      port: 3131
      targetPort: country-http-3
